/**
 * Short, stable CSS selectors for breadcrumbs, element reports and heatmaps.
 *
 * Stability beats precision: a selector that survives a redeploy groups
 * reports on "the same button" across releases. So we prefer author-given
 * identity (a hand-written id, `data-testid`, `data-spotter-id`) and only
 * then fall back to a short `:nth-of-type` path, capped in depth.
 */

const TEST_ATTRS = ["data-spotter-id", "data-testid", "data-test-id", "data-test", "data-cy", "data-qa"];
const MAX_DEPTH = 5;

/** CSS.escape where available (browsers), a conservative fallback elsewhere. */
export function cssEscape(value: string): string {
  const css = (globalThis as { CSS?: { escape?: (v: string) => string } }).CSS;
  if (css?.escape) return css.escape(value);
  return value.replace(/^(\d)/, "\\3$1 ").replace(/[^\w-]/g, (c) => `\\${c}`);
}

/**
 * Ids generated by frameworks (`:r1:`, `radix-12`, `mui-3485`, `ember123`,
 * long hex/uuid runs) change between renders or builds: don't anchor on them.
 */
function isStableId(id: string): boolean {
  if (!id || id.length > 64) return false;
  if (/[:]/.test(id)) return false;
  if (/\d{3,}/.test(id)) return false;
  if (/^[0-9a-f-]{16,}$/i.test(id)) return false;
  if (/^(?:radix|mui|headlessui|react-aria|ember|ext-gen|yui)[-_]/i.test(id)) return false;
  return true;
}

function unique(root: ParentNode, selector: string, el: Element): boolean {
  try {
    const found = root.querySelectorAll(selector);
    return found.length === 1 && found[0] === el;
  } catch {
    return false;
  }
}

/** The node's own anchor (`#id`, `[data-testid="…"]`), if it has a stable one. */
function anchorOf(el: Element): string | null {
  const id = el.getAttribute("id");
  if (id && isStableId(id)) return `#${cssEscape(id)}`;
  for (const attr of TEST_ATTRS) {
    const v = el.getAttribute(attr);
    if (v && v.length <= 100) return `[${attr}="${v.replace(/["\\]/g, "\\$&")}"]`;
  }
  return null;
}

function segmentOf(el: Element): string {
  const tag = el.localName || el.nodeName.toLowerCase();
  const parent = el.parentElement;
  if (!parent) return tag;
  let index = 0;
  let count = 0;
  for (let sib = parent.firstElementChild; sib; sib = sib.nextElementSibling) {
    if (sib.localName === el.localName) {
      count++;
      if (sib === el) index = count;
    }
  }
  return count > 1 ? `${tag}:nth-of-type(${index})` : tag;
}

/**
 * A short, stable, unique-ish selector for `el`, within its root (document or
 * shadow root). Inside a shadow root the host's selector is prefixed with
 * ` >>> ` (informational; the shadow part alone is a valid selector).
 */
export function cssSelector(el: Element): string {
  try {
    const root = el.getRootNode() as ParentNode & { host?: Element };
    const inner = selectorWithin(el, root);
    if (root && root.host && root.nodeType === 11) return `${cssSelector(root.host)} >>> ${inner}`;
    return inner;
  } catch {
    try {
      return el.localName || "unknown";
    } catch {
      return "unknown";
    }
  }
}

function selectorWithin(el: Element, root: ParentNode): string {
  const own = anchorOf(el);
  if (own && unique(root, own, el)) return own;

  const parts: string[] = [];
  let node: Element | null = el;
  for (let depth = 0; node && depth < MAX_DEPTH; depth++) {
    const tag = node.localName;
    if (tag === "html" || tag === "body" || tag === "head") {
      parts.unshift(tag);
      break;
    }
    const anchor = depth > 0 ? anchorOf(node) : null;
    if (anchor && unique(root, anchor, node)) {
      parts.unshift(anchor);
      break;
    }
    parts.unshift(segmentOf(node));
    const candidate = parts.join(" > ");
    if (unique(root, candidate, el)) return candidate;
    node = node.parentElement;
  }
  return parts.join(" > ");
}
