// Generated by withSpotter() from next.config — do not edit; it is rewritten on every build.
// Commit it so type checks in CI see the same feature flags as the build.
import type {} from "@trusplex/spotter/core";

type SpotterJson = string | number | boolean | null | SpotterJson[] | { [key: string]: SpotterJson };

declare module "@trusplex/spotter/core" {
  interface SpotterFeatureFlags {
    analytics: true;
    annotate: true;
    flags: true;
    recording: true;
    replay: true;
    screenshot: true;
    widget: true;
  }
  interface SpotterRegister {
    events: "checkout_started" | "checkout_failed" | "signup_completed";
    fields: {
      order_number: string;
      plan: "free" | "pro";
    };
    contexts: {
      cart: { [key: string]: SpotterJson };
    };
  }
}
