/**
 * The generated `spotter-env.d.ts`: feature flags and registered names as
 * types, so `spotter.track()` with analytics compiled out, or an event name
 * that isn't registered, is a TypeScript error (see `core/typed.ts`).
 *
 * Pure string generation; `withSpotter()` writes it (only when the content
 * changed, so it never dirties git or retriggers watchers needlessly).
 */
import type { FeatureName } from "../../../core/features.ts";
import type { CustomFieldType } from "../../../core/schema.ts";

export type FieldTypeSpec = CustomFieldType | { type: CustomFieldType; options?: readonly string[] };

export interface SpotterTypesOptions {
  /** Custom analytics event names (`spotter.track(name)`). */
  events?: readonly string[];
  /** Custom field ids and their types; `select` options become a string-literal union. */
  fields?: Record<string, FieldTypeSpec>;
  /** Named contexts (`spotter.setContext(name, …)`). */
  contexts?: readonly string[];
}

const lit = (s: string) => JSON.stringify(s);
const key = (s: string) => (/^[A-Za-z_$][\w$]*$/.test(s) ? s : lit(s));

function fieldType(spec: FieldTypeSpec): string {
  const type = typeof spec === "string" ? spec : spec.type;
  const options = typeof spec === "string" ? undefined : spec.options;
  const union = options && options.length > 0 ? options.map(lit).join(" | ") : "string";
  switch (type) {
    case "select":
      return union;
    case "multiselect":
      return options && options.length > 0 ? `(${union})[]` : "string[]";
    case "file":
      return "string[]";
    case "checkbox":
      return "boolean";
    case "rating":
      return "number";
    default:
      return "string";
  }
}

export function generateEnvDts(features: Record<FeatureName, boolean>, types: SpotterTypesOptions = {}): string {
  const flags = (Object.keys(features) as FeatureName[])
    .sort()
    .map((f) => `    ${f}: ${features[f]};`)
    .join("\n");
  const register: string[] = [];
  if (types.events && types.events.length > 0) {
    register.push(`    events: ${[...new Set(types.events)].map(lit).join(" | ")};`);
  }
  if (types.fields && Object.keys(types.fields).length > 0) {
    const body = Object.entries(types.fields)
      .map(([id, spec]) => `      ${key(id)}: ${fieldType(spec)};`)
      .join("\n");
    register.push(`    fields: {\n${body}\n    };`);
  }
  if (types.contexts && types.contexts.length > 0) {
    const body = [...new Set(types.contexts)].map((c) => `      ${key(c)}: { [key: string]: SpotterJson };`).join("\n");
    register.push(`    contexts: {\n${body}\n    };`);
  }
  return `// Generated by withSpotter() from next.config — do not edit; it is rewritten on every build.
// Commit it so type checks in CI see the same feature flags as the build.
import type {} from "@trusplex/spotter/core";

type SpotterJson = string | number | boolean | null | SpotterJson[] | { [key: string]: SpotterJson };

declare module "@trusplex/spotter/core" {
  interface SpotterFeatureFlags {
${flags}
  }
  interface SpotterRegister {
${register.join("\n")}
  }
}
`.replace(/interface SpotterRegister \{\n\n  \}/, "interface SpotterRegister {}");
}
